name: Andy Dote
description: Andy Dote's blog
url: http://andydote.co.uk
markdown: redcarpet
highlighter: pygments
exclude: [serve, servedrafts, vagrantfile]
paginate: 5
gems: [jekyll-paginate]

ftp_host: 'andydote.co.uk'
ftp_dir: '/public_html'
ftp_passive: false
